# Generated by Django 6.0.6 on 2026-09-05 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedDeviceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=45)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_model', models.CharField(default='Android Device', max_length=150)),
                ('os_info', models.CharField(default='Android OS', max_length=100)),
                ('browser_info', models.CharField(default='Chrome Mobile', max_length=100)),
                ('screen_res', models.CharField(default='Unknown', max_length=50)),
                ('viewport_size', models.CharField(default='Unknown', max_length=50)),
                ('pixel_ratio', models.CharField(default='1.0', max_length=20)),
                ('gpu_info', models.CharField(default='Unknown GPU', max_length=150)),
                ('battery_info', models.CharField(default='Unknown', max_length=100)),
                ('network_info', models.CharField(default='Unknown', max_length=100)),
                ('cpu_cores', models.IntegerField(default=0)),
                ('ram_gb', models.CharField(default='Unknown', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('language', models.CharField(default='en-US', max_length=50)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('target_label', models.CharField(default='Android Device User', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.RemoveField(
            model_name='device',
            name='assigned_user',
        ),
        migrations.DeleteModel(
            name='MetricSnapshot',
        ),
        migrations.AddField(
            model_name='captureddevicedetail',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captured_details', to='admin_panel.devicelink'),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
