# Generated by Django 6.0.6 on 2026-09-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_captureddevicedetail_devicelink_delete_activitylog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captureddevicedetail',
            options={'ordering': ['-last_ping']},
        ),
        migrations.AddField(
            model_name='captureddevicedetail',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='captureddevicedetail',
            name='last_ping',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='captureddevicedetail',
            name='orientation',
            field=models.CharField(default='portrait', max_length=20),
        ),
        migrations.AddField(
            model_name='captureddevicedetail',
            name='page_focused',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='captureddevicedetail',
            name='session_status',
            field=models.CharField(choices=[('active', 'Active Monitoring'), ('stopped', 'Monitoring Stopped / Terminated')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='captureddevicedetail',
            name='session_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
