# Generated by Django 6.0.6 on 2026-09-05 15:23

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_captureddevicedetail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('asset_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('device_model', models.CharField(default='Android Enterprise Device', max_length=100)),
                ('os_info', models.CharField(default='Android OS', max_length=100)),
                ('admin_active', models.BooleanField(default=False)),
                ('password_compliant', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_compliance_check', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='captureddevicedetail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='devicelink',
            options={},
        ),
        migrations.RemoveField(
            model_name='devicelink',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='captureddevicedetail',
            name='browser_info',
            field=models.CharField(default='Unknown Browser', max_length=100),
        ),
        migrations.AlterField(
            model_name='captureddevicedetail',
            name='device_model',
            field=models.CharField(default='Unknown Device', max_length=100),
        ),
        migrations.AlterField(
            model_name='captureddevicedetail',
            name='gpu_info',
            field=models.CharField(default='Unknown GPU', max_length=200),
        ),
        migrations.AlterField(
            model_name='captureddevicedetail',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='captureddevicedetail',
            name='last_ping',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='captureddevicedetail',
            name='orientation',
            field=models.CharField(default='portrait', max_length=30),
        ),
        migrations.AlterField(
            model_name='captureddevicedetail',
            name='os_info',
            field=models.CharField(default='Android', max_length=100),
        ),
        migrations.AlterField(
            model_name='captureddevicedetail',
            name='ram_gb',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='captureddevicedetail',
            name='session_status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='captureddevicedetail',
            name='session_token',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='captureddevicedetail',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='devicelink',
            name='target_label',
            field=models.CharField(default='Android User', max_length=100),
        ),
    ]
