# Generated by Django 6.0.6 on 2026-09-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_enterpriseasset_alter_captureddevicedetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureddevicedetail',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='captureddevicedetail',
            name='location_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='captureddevicedetail',
            name='location_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='captureddevicedetail',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='captureddevicedetail',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CapturedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='captured_videos/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('duration_sec', models.IntegerField(default=0)),
                ('file_size_mb', models.CharField(default='0 MB', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_videos', to='admin_panel.captureddevicedetail')),
            ],
        ),
    ]
