# Generated by Django 6.0.6 on 2026-09-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_captureddevicedetail_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureddevicedetail',
            name='location_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
